# Generated by Django 4.2.4 on 2025-10-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_competition_logo_alter_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('matchweek', models.IntegerField()),
                ('result', models.CharField(max_length=1)),
                ('y_home_goals', models.IntegerField()),
                ('y_away_goals', models.IntegerField()),
                ('home_gf', models.FloatField(blank=True, null=True)),
                ('home_ga', models.FloatField(blank=True, null=True)),
                ('home_xg', models.FloatField(blank=True, null=True)),
                ('away_gf', models.FloatField(blank=True, null=True)),
                ('away_ga', models.FloatField(blank=True, null=True)),
                ('away_xg', models.FloatField(blank=True, null=True)),
                ('table_points_gap', models.FloatField(blank=True, null=True)),
                ('home_rank_in_season', models.IntegerField(blank=True, null=True)),
                ('away_rank_in_season', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='home.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='home.team')),
            ],
        ),
    ]
