# Generated by Django 4.2.4 on 2025-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_match_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='y_away_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='y_home_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
