# Generated by Django 4.2.4 on 2025-12-19 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-date_parsed']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_ga',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_gf',
        ),
        migrations.RemoveField(
            model_name='match',
            name='away_rank_in_season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_ga',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_gf',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_rank_in_season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='matchweek',
        ),
        migrations.RemoveField(
            model_name='match',
            name='played',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='table_points_gap',
        ),
        migrations.RemoveField(
            model_name='match',
            name='y_away_goals',
        ),
        migrations.RemoveField(
            model_name='match',
            name='y_home_goals',
        ),
        migrations.AddField(
            model_name='match',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='date_parsed',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='game_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_hour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_report',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season'], name='home_match_season_fd0b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date_parsed'], name='home_match_date_pa_17f5fe_idx'),
        ),
    ]
