# Generated by Django 4.2.4 on 2025-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_match_options_remove_match_away_ga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('season', 'date', 'home_team', 'away_team'), name='unique_match_per_day_per_season'),
        ),
    ]
