# Generated by Django 4.2.4 on 2025-12-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_match_game_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('nation', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('born', models.PositiveIntegerField(blank=True, null=True)),
                ('season', models.CharField(max_length=10)),
                ('playing_time_mp', models.PositiveIntegerField(blank=True, null=True)),
                ('playing_time_starts', models.PositiveIntegerField(blank=True, null=True)),
                ('playing_time_min', models.PositiveIntegerField(blank=True, null=True)),
                ('playing_time_90s', models.FloatField(blank=True, null=True)),
                ('goals', models.PositiveIntegerField(blank=True, null=True)),
                ('assists', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_assists', models.PositiveIntegerField(blank=True, null=True)),
                ('goals_non_penalty', models.PositiveIntegerField(blank=True, null=True)),
                ('penalties_scored', models.PositiveIntegerField(blank=True, null=True)),
                ('penalties_attempted', models.PositiveIntegerField(blank=True, null=True)),
                ('yellow_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('red_cards', models.PositiveIntegerField(blank=True, null=True)),
                ('xg', models.FloatField(blank=True, null=True)),
                ('npxg', models.FloatField(blank=True, null=True)),
                ('xag', models.FloatField(blank=True, null=True)),
                ('npxg_xag', models.FloatField(blank=True, null=True)),
                ('progressive_carries', models.PositiveIntegerField(blank=True, null=True)),
                ('progressive_passes', models.PositiveIntegerField(blank=True, null=True)),
                ('progressive_runs', models.PositiveIntegerField(blank=True, null=True)),
                ('p90_goals', models.FloatField(blank=True, null=True)),
                ('p90_assists', models.FloatField(blank=True, null=True)),
                ('p90_goals_assists', models.FloatField(blank=True, null=True)),
                ('p90_goals_non_penalty', models.FloatField(blank=True, null=True)),
                ('p90_goals_assists_non_penalty', models.FloatField(blank=True, null=True)),
                ('p90_xg', models.FloatField(blank=True, null=True)),
                ('p90_xag', models.FloatField(blank=True, null=True)),
                ('p90_xg_xag', models.FloatField(blank=True, null=True)),
                ('p90_npxg', models.FloatField(blank=True, null=True)),
                ('p90_npxg_xag', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_stats', to='home.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_season_stats', to='home.team')),
            ],
            options={
                'ordering': ['-playing_time_min'],
                'unique_together': {('player_id', 'season')},
            },
        ),
    ]
