# Generated by Django 4.2.4 on 2025-12-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_playerseasonstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('goals', models.PositiveIntegerField(blank=True, null=True)),
                ('assists', models.PositiveIntegerField(blank=True, null=True)),
                ('xg', models.FloatField(blank=True, null=True)),
                ('xag', models.FloatField(blank=True, null=True)),
                ('touches', models.PositiveIntegerField(blank=True, null=True)),
                ('progressive_passes', models.PositiveIntegerField(blank=True, null=True)),
                ('progressive_carries', models.PositiveIntegerField(blank=True, null=True)),
                ('take_ons_attempted', models.PositiveIntegerField(blank=True, null=True)),
                ('take_ons_successful', models.PositiveIntegerField(blank=True, null=True)),
                ('tackles', models.PositiveIntegerField(blank=True, null=True)),
                ('interceptions', models.PositiveIntegerField(blank=True, null=True)),
                ('blocks', models.PositiveIntegerField(blank=True, null=True)),
                ('sca', models.PositiveIntegerField(blank=True, null=True)),
                ('gca', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='home.competition')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='home.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='home.playerseasonstat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='home.team')),
            ],
            options={
                'ordering': ['-match__date_parsed'],
                'indexes': [models.Index(fields=['season'], name='home_player_season_1e24bc_idx'), models.Index(fields=['player'], name='home_player_player__fe3ab3_idx'), models.Index(fields=['match'], name='home_player_match_i_5477c1_idx')],
                'unique_together': {('match', 'player')},
            },
        ),
    ]
