# Generated by Django 4.2.4 on 2025-12-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_playermatchstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstat',
            name='blocks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='challenge_success_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='challenges_lost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='clearances',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='crosses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='errors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='expected_assists',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='interceptions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='key_passes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='long_pass_completion_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='medium_pass_completion_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='pass_completion_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_attempted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_blocked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_completed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_into_final_third',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_into_penalty_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='passes_offside',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='progressive_pass_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='short_pass_completion_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='switches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles_attacking_third',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles_defensive_third',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles_interceptions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles_middle_third',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='tackles_won',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseasonstat',
            name='through_balls',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['season'], name='home_player_season_4a4c35_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['team'], name='home_player_team_id_e9d9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='playerseasonstat',
            index=models.Index(fields=['league'], name='home_player_league__bf48e8_idx'),
        ),
    ]
