# Generated by Django 4.2.4 on 2025-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_playerseasonstat_blocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
